import {ECode, ECodeCategories, ECodeStatusMap, ECodeStatusMapItem} from './type'


export const eCodeCategoriesData: ECodeCategories[] = [
  { id: "colors", name: "Красители" },
  { id: "preservatives", name: "Консерванты" },
  { id: "antioxidants", name: "Антиоксиданты" },
  { id: "acidity-regulators", name: "Регуляторы кислотности" },
  { id: "thickeners", name: "Загустители" },
  { id: "emulsifiers", name: "Эмульгаторы" },
  { id: "flavor-enhancers", name: "Усилители вкуса" },
  { id: "sweeteners", name: "Подсластители" },
  { id: "other", name: "Другие добавки" },
];

export const eCodeStatusMapData: ECodeStatusMap = {
  halal: {
    label: "Халяль",
    status: "halal",
    description: "Разрешено для употребления мусульманами",
  },
  haram: {
    label: "Харам",
    status: "haram",
    description: "Запрещено для употребления мусульманами",
  },
  mushbooh: {
    label: "Машбух",
    status: "mushbooh",
    description: "Сомнительно, требует дополнительной проверки",
  },
  unknown: {
    label: "Неизвестно",
    status: "unknown",
    description: "Статус не определен",
  },
}


export const eCodesData: ECode[] = [
  {
    code: "E100",
    name: "Curcumin",
    nameRu: "Куркумин",
    category: "colors",
    status: "halal",
    source: "Plant-based (turmeric)",
    description: "A yellow food coloring derived from turmeric root.",
    descriptionRu: "Желтый краситель, получаемый из корня куркумы.",
  },
  {
    code: "E101",
    name: "Riboflavin (Vitamin B2)",
    nameRu: "Рибофлавин (Витамин B2)",
    category: "colors",
    status: "halal",
    source: "Synthetic or bacterial fermentation",
    description: "A yellow to orange-yellow colored vitamin used as a food coloring.",
    descriptionRu: "Витамин желто-оранжевого цвета, используемый в качестве пищевого красителя.",
  },
  {
    code: "E120",
    name: "Carmine (Cochineal)",
    nameRu: "Кармин (Кошениль)",
    category: "colors",
    status: "haram",
    source: "Insect-based (cochineal beetles)",
    description: "A red dye produced from cochineal insects.",
    descriptionRu: "Красный краситель, получаемый из насекомых кошенили.",
  },
  {
    code: "E160a",
    name: "Alpha-carotene, Beta-carotene",
    nameRu: "Альфа-каротин, Бета-каротин",
    category: "colors",
    status: "halal",
    source: "Plant-based or synthetic",
    description: "Orange pigment found in many plants, especially carrots.",
    descriptionRu: "Оранжевый пигмент, содержащийся во многих растениях, особенно в моркови.",
  },
  {
    code: "E210",
    name: "Benzoic acid",
    nameRu: "Бензойная кислота",
    category: "preservatives",
    status: "halal",
    source: "Synthetic or natural",
    description: "Used as a preservative to prevent the growth of microorganisms.",
    descriptionRu: "Используется как консервант для предотвращения роста микроорганизмов.",
  },
  {
    code: "E220",
    name: "Sulfur dioxide",
    nameRu: "Диоксид серы",
    category: "preservatives",
    status: "halal",
    source: "Synthetic",
    description: "Used as a preservative and antioxidant, particularly in wines and dried fruits.",
    descriptionRu: "Используется как консервант и антиоксидант, особенно в винах и сухофруктах.",
  },
  {
    code: "E300",
    name: "Ascorbic acid (Vitamin C)",
    nameRu: "Аскорбиновая кислота (Витамин C)",
    category: "antioxidants",
    status: "halal",
    source: "Synthetic or natural",
    description: "Used as an antioxidant and nutrient supplement.",
    descriptionRu: "Используется как антиоксидант и пищевая добавка.",
  },
  {
    code: "E322",
    name: "Lecithins",
    nameRu: "Лецитины",
    category: "emulsifiers",
    status: "mushbooh",
    source: "Plant-based (soy, sunflower) or animal-based",
    description: "Used as an emulsifier. Can be derived from both plant and animal sources.",
    descriptionRu: "Используется как эмульгатор. Может быть получен как из растительных, так и из животных источников.",
  },
  {
    code: "E422",
    name: "Glycerol",
    nameRu: "Глицерин",
    category: "thickeners",
    status: "mushbooh",
    source: "Plant-based or animal-based",
    description: "Used as a sweetener, solvent, and preservative. Can be derived from both plant and animal sources.",
    descriptionRu:
      "Используется как подсластитель, растворитель и консервант. Может быть получен как из растительных, так и из животных источников.",
  },
  {
    code: "E471",
    name: "Mono- and diglycerides of fatty acids",
    nameRu: "Моно- и диглицериды жирных кислот",
    category: "emulsifiers",
    status: "mushbooh",
    source: "Plant-based or animal-based",
    description: "Used as emulsifiers. Can be derived from both plant and animal sources.",
    descriptionRu:
      "Используются как эмульгаторы. Могут быть получены как из растительных, так и из животных источников.",
  },
  {
    code: "E542",
    name: "Bone phosphate",
    nameRu: "Костный фосфат",
    category: "acidity-regulators",
    status: "haram",
    source: "Animal-based (bones)",
    description: "Used as an anti-caking agent and acidity regulator. Derived from animal bones.",
    descriptionRu: "Используется как антислеживающий агент и регулятор кислотности. Получают из костей животных.",
  },
  {
    code: "E621",
    name: "Monosodium glutamate (MSG)",
    nameRu: "Глутамат натрия",
    category: "flavor-enhancers",
    status: "halal",
    source: "Fermentation of plant-based materials",
    description: "Used as a flavor enhancer in many processed foods.",
    descriptionRu: "Используется как усилитель вкуса во многих обработанных пищевых продуктах.",
  },
  {
    code: "E631",
    name: "Sodium inosinate",
    nameRu: "Инозинат натрия",
    category: "flavor-enhancers",
    status: "mushbooh",
    source: "Meat or plant-based",
    description: "Used as a flavor enhancer. Can be derived from meat or plant sources.",
    descriptionRu: "Используется как усилитель вкуса. Может быть получен из мяса или растительных источников.",
  },
  {
    code: "E901",
    name: "Beeswax",
    nameRu: "Пчелиный воск",
    category: "other",
    status: "halal",
    source: "Insect-based (bees)",
    description: "Used as a glazing agent. Produced by honeybees.",
    descriptionRu: "Используется как глазирующий агент. Производится медоносными пчелами.",
  },
  {
    code: "E904",
    name: "Shellac",
    nameRu: "Шеллак",
    category: "other",
    status: "halal",
    source: "Insect-based (lac insects)",
    description: "Used as a glazing agent. Secreted by the female lac bug.",
    descriptionRu: "Используется как глазирующий агент. Выделяется самками лаковых червецов.",
  },
  {
    code: "E951",
    name: "Aspartame",
    nameRu: "Аспартам",
    category: "sweeteners",
    status: "halal",
    source: "Synthetic",
    description: "An artificial non-saccharide sweetener used as a sugar substitute.",
    descriptionRu: "Искусственный подсластитель, используемый как заменитель сахара.",
  },
  {
    code: "E967",
    name: "Xylitol",
    nameRu: "Ксилит",
    category: "sweeteners",
    status: "halal",
    source: "Plant-based",
    description: "A sugar alcohol used as a sweetener. Extracted from birch wood or produced from corn cobs.",
    descriptionRu:
      "Сахарный спирт, используемый как подсластитель. Извлекается из березовой древесины или производится из кукурузных початков.",
  },
  {
    code: "E999",
    name: "Quillaia extract",
    nameRu: "Экстракт квиллайи",
    category: "other",
    status: "halal",
    source: "Plant-based (Quillaja saponaria tree)",
    description: "Used as a foaming agent in beverages. Extracted from the bark of the Quillaja saponaria tree.",
    descriptionRu: "Используется как пенообразователь в напитках. Извлекается из коры дерева Quillaja saponaria.",
  },
  {
    code: "E995",
    name: "Quillaia extract",
    nameRu: "Экстракт квиллайи",
    category: "other",
    status: "unknown",
    source: "Plant-based (Quillaja saponaria tree)",
    description: "Used as a foaming agent in beverages. Extracted from the bark of the Quillaja saponaria tree.",
    descriptionRu: "Используется как пенообразователь в напитках. Извлекается из коры дерева Quillaja saponaria.",
  },
]
